### ISSUE TITLE
建议-优化操作流程

### ISSUE THREAD

**Issue by wrr008123** [eightfeet/yugong#12]
简单试了一下编辑移动页面，这个操作流程有点麻烦

添加组件每次都需要点击【添加组件】，然后弹出组件选择列表，下次添加组件还要重复这个过程

建议试一下其他相关产品，然后借鉴一下

**Comment by eightfeet** [comment]
非常感谢您的反馈，我会慎重考虑你的意见，当前的设计思想是保证使用者专注于展示面板与配置面板，所以未展示组件面板，展示过多内容容易干扰用户的专注力，毕竟配置本身是个复杂过程，至于需要复用某些组件完全可以通过复制按钮来快速复制组件
